config/routes.rb
Bloomberg::Application.routes.draw do
  devise_for :users

  resources :portfolios do
    collection do 
      get 'preference'
      post 'make_transaction'
      post 'send_alert'
      post 'set_prefs'
    end
  end
  resources :users

  root to: "static_pages#home"

  match 'charts', to: 'static_pages#charts'
  match 'preference', to: 'static_pages#preference'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">     
    <div class="navbar-header">
      <!-- nav button icon for smaller resolutions (mobile) -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>          
    </div>
    <!-- top left logo --> 
    <!-- <a class="navbar-brand" href="index.html">Logo la</a> -->
    <ul class="nav navbar-nav">
      <li><%= link_to "Portfolio Summary", "/" %></li>
    </ul>

    <!-- nav options -->
    <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "My Portfolio", "/" %></li>
        <li><%= link_to "Preferences", "/portfolios/preference" %></li>
      <% if signed_in? %>
        <li><%= link_to "Sign Out", destroy_user_session_path, {class: "nav-links", method: :delete} %></li>
      <% else %>
        <li><%= link_to "Sign In", new_user_session_path, class: "nav-links" %></li>
        <li><%= link_to "Sign Up", new_registration_path(:user), class: "nav-links" %></li>
      <% end %>
      </ul>
    </div>
  </div><!-- container -->
</nav>

<br /><br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloomberg</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>